### PR TITLE
Version 1.0.1 Fixes

### PR DESCRIPTION
**Pull request by capcor**
1.0.1

-Fixes keyboard layout to be a normal layout
-Now tells you what the word was on the "share" screen (previously the correct word was a mystery if you got it incorrect)
-Added missing and valid words present in the solutions file but not present in the words file

### CODE REVIEW

**Comment by AM7999** [comment]
love.graphics.print("Fixes by CapCor", 480, 56) :sob:

**Comment by capcor** [comment]
Scream

**Comment by htv04** [comment]
Hmm, interesting that your self-promo wasn't added to the PR notes :thinking: 

Including that, the version bump and keyboard changes are pretty unnecessary. The keyboard is designed after Wordle's, which has enter at the bottom left and backspace at the bottom right.

About the missing words, the issue is really with the solution list, not the word list. The missing words from the solutions should be removed because they're not real words. No idea why they were included in the list of the common words I used.

The only useful change I see here is the noting of the correct word on the score screen, which I'll accept as a separate PR if you're willing to make one. For future reference, please make PRs with one important change at a time.

**Comment by capcor** [comment]
I thought maybe you added some of those words as a some sort of geeky reference or something. I didn't want to remove those words since maybe you wanted those words in there. Which is pretty funny since I added my own name, I honestly just wanted to see what your reaction would be. I understand the keyboard layout but I still think the wordle layout is a bit awkward but I suppose that should stay if wordle is like that.

**Pull request closed without merging**
